### ISSUE TITLE
Fix for @mock command -v doesn't work for conditions

### ISSUE THREAD

**Issue by verdx** [bach-sh/bach#7]
Hi, after the fix https://github.com/bach-sh/bach/commit/71471d0618474e461256831b842ec99cf0f9b352, 
``` 
@mock command -v example === @echo "Example"
```
works perfectly, but I have seen it doesn't work when used in a condition as so:
```
test-script () {
    @mock command -v example === @echo "Example"
    if [ -n "$(command -v example)" ]
        echo "Works!"
    fi
}
test-script-assert() {
    echo "Works!"
}
```
It does work when using `command example`, without `-v`

**Comment by chaifeng** [comment]
Done
